### PR TITLE
Android App Bundle Support Added

### PR DESCRIPTION
**Pull request by mirsamantajbakhsh**
Dear Claudiu,
First of all I wanted to thank you for creating Obfuscapk. I saw some issues in your repository about working with Android Bundle, beside APK files. Therefore, I've added AAB support to obfuscapk using other repository named [BundleDecompiler](https://github.com/TamilanPeriyasamy/BundleDecompiler). I have tested and the results were OK.

Please help me if there are other works I should have done.

Best Regards,
Dr. Tajbakhsh

### CODE REVIEW

**Comment by mirsamantajbakhsh** [comment]
Checks are failing since in the test environment, there is no `BundleDecompiler.jar` in `/usr/bin/BundleDecompiler.jar`. I do not know how to fix tests.

**Comment by ClaudiuGeorgiu** [comment]
Hi @mirsamantajbakhsh, this looks very interesting! Bundle support has been a long desired feature and now you implemented it, so thank you! Here are my thoughts:
1. BundleDecompiler doesn't support windows, I would prefer a cross platform solution but that's ok, however, we have to add some code to show some sort of warning if the user tries to use Obfuscapk on a bundle file on windows;
2. the code for BundleDecompiler is not available and it's not clear under what license is distributed, I'm not super happy but I can live with it;
3. as you wrote earlier, the test environment needs to be updated to fix the tests. I can help with this, if you [allow me to push commits to your branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) I will update the GitHub Actions workflow files and the tests should work again (otherwise I can fix this after merging, no problem).

**Comment by mirsamantajbakhsh** [comment]
> Hi @mirsamantajbakhsh, this looks very interesting! Bundle support has been a long desired feature and now you implemented it, so thank you! Here are my thoughts:
> 
> 1. BundleDecompiler doesn't support windows, I would prefer a cross platform solution but that's ok, however, we have to add some code to show some sort of warning if the user tries to use Obfuscapk on a bundle file on windows;
> 2. the code for BundleDecompiler is not available and it's not clear under what license is distributed, I'm not super happy but I can live with it;
> 3. as you wrote earlier, the test environment needs to be updated to fix the tests. I can help with this, if you [allow me to push commits to your branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) I will update the GitHub Actions workflow files and the tests should work again (otherwise I can fix this after merging, no problem).

Dear @ClaudiuGeorgiu,
Thanks slot for your kind comments. I have checked the BundleDecompiler. The author has said that the code will be published. I will check regularly if the code is published and Windows support is added to BundleDecompiler.

About write access, I have checked "Allow edits by maintainers". Furthermore, I added you as collaborator to my branch of Obfuscapk.

I'm very proud to take a small part in your amazing project. 🙏

**Comment by ClaudiuGeorgiu** [comment]
I made a few changes and merged your PR, thank you very much @mirsamantajbakhsh, I'm glad you found this project interesting and decided to contribute!

**Pull request merged**
